version: '3'
services:
  springboot:
    build: ./
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.32
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    restart: always
    container_name: springboot-mysql
    ports:
      - '3306:3306'
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_USER=root
      - BITNAMI_DEBUG=true
    volumes:
      - ./data/data:/var/lib/mysql
      - ./data/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/sql:/docker-entrypoint-initdb.d