spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://springboot-dameng8:5236?schema=SPRINGBOOT&compatibleMode=mysql&characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: SYSDBA
    password: SYSDBA001
